# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: CS 324
tagline: CS 324 - Advances in Foundation Models
description: Understanding and building on foundation models.
author: Michael Zhang
baseurl: '/winter2023'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
markdown: kramdown

# Theme settings
# remote_theme: pmarsceill/just-the-docs@v0.3.3
remote_theme: just-the-docs/just-the-docs@v0.4.0.rc3
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Winter 2022:
    - 'https://stanford-cs324.github.io/winter2022/'
# footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
  lectures:
  projects:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/images/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement
  - scope:
      path: ''
      type: lectures
    values:
      layout: lecture

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag